language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - "pip install flake8"
  - "pip install tornado passlib"
  - "pip install python-dateutil"
script:
  - "make test"
notifications:
  email:
    - phihag@phihag.de
    - martin.dessauer@t-online.de
